### ISSUE TITLE
Configure the app to use images stored locally or remotely

### ISSUE THREAD

**Issue by arnikz** [LINNAE-project/SFB-Annotator#42]
Currently, the images are only served through the local FS

https://github.com/LINNAE-project/SFB-Annotator/blob/5e138bb0d2bc33ac93699e38b0f5996729563fcc/src/main/java/localdomain/localhost/servlets/FileServlet.java#L32

for example, at http://localhost:8080/semanticAnnotator/files/MMNAT01_AF_NNM001001033_001.jpg.

the input JSON includes a base URL

https://github.com/LINNAE-project/SFB-Annotator/blob/73f6788cb706d0d4ec8e04e7ea16f9920a2f350a/data/json/example_1_1.json#L16

but not used directly in the RDF transformation to generate rely (local) IRIs

https://github.com/LINNAE-project/SFB-Annotator/blob/5e138bb0d2bc33ac93699e38b0f5996729563fcc/src/main/java/localdomain/localhost/servlets/writeAnnotationsToRDF.java#L189-L190

the image viewer relies on the following source URLs (e.g. http://localhost:8080/semanticAnnotator/files/MMNAT01_AF_NNM001001033_001.jpg)

https://github.com/LINNAE-project/SFB-Annotator/blob/73f6788cb706d0d4ec8e04e7ea16f9920a2f350a/src/main/webapp/js/components/ImageViewer.js#L90

and on a hard-coded list of image filenames -> use full URLs

https://github.com/LINNAE-project/SFB-Annotator/blob/5e138bb0d2bc33ac93699e38b0f5996729563fcc/src/main/webapp/data/data.json#L1-L19

See related issues (#33 and #35).

**Comment by arnikz** [comment]
TODO: update CI to test remote access

**Comment by arnikz** [comment]
The app is configured to access images stored locally (default). To configure it for remote access (e.g. using the SDR archive):
```
JSON=/usr/local/tomcat/webapps/semanticAnnotator/data/
docker exec -it sea bash -c "cp $JSON/data-remote.json $JSON/data.json"
```
or see [README.md](https://github.com/LINNAE-project/SFB-Annotator/blob/iss42/README.md)

**Comment by arnikz** [comment]
Cantaloupe fails to serve [`info.json`](http://localhost:8182/iiif/2/900c341c1c10fff7%2Ffiles%2FMMNAT01_PM_NNM001001033_001/info.json) including the images from the remote:

```

403 Forbidden

https://trng-repository.surfsara.nl/deposit/900c341c1c10fff7/files/MMNAT01_PM_NNM001001033_001.tif

java.nio.file.AccessDeniedException: https://trng-repository.surfsara.nl/deposit/900c341c1c10fff7/files/MMNAT01_PM_NNM001001033_001.tif
	at edu.illinois.library.cantaloupe.source.HttpSource.request(HttpSource.java:490)
	at edu.illinois.library.cantaloupe.source.HttpSource.request(HttpSource.java:458)
	at edu.illinois.library.cantaloupe.source.HttpSource.fetchHEADResponseInfo(HttpSource.java:433)
	at edu.illinois.library.cantaloupe.source.HttpSource.checkAccess(HttpSource.java:259)
	at edu.illinois.library.cantaloupe.resource.iiif.v2.InformationResource.doGET(InformationResource.java:112)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.handle(HandlerServlet.java:98)
	at edu.illinois.library.cantaloupe.resource.HandlerServlet.doGet(HandlerServlet.java:36)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1391)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:760)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:547)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by arnikz** [comment]
Quick fix [here](https://github.com/LINNAE-project/docker-cantaloupe/commit/4f593148f7d1b83bb684cde223f860c3f33b29a3).
